[package]
name = "format_trace"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = "1.0.204"
serde_json = { version = "1.0", features = ["preserve_order"] }
regex = "1.10.5"

[lib]
name = "format_trace"
path = "src/lib.rs"
