watcher_map = [
    ["0", "0", "0", "0", "0", "0", "0", "0"], 
    ["0", "0", "0", "0", "0", "0", "0", "0"], 
    ["0", "0", "0", "0", "0", "0", "0", "0"], 
    ["0", "0", "0", "0", "0", "0", "0", "0"], 
    ["0", "0", "0", "0", "0", "0", "0", "0"], 
    ["0", "0", "0", "1", "0", "0", "0", "0"], 
    ["0", "0", "0", "0", "0", "0", "0", "0"], 
    ["0", "1", "0", "0", "1", "1", "0", "0"]
]

dagger_x = "5"
dagger_y = "4"

path_x = ["0", "1", "0", "1", "0", "1", "3", "5"]
path_y = ["0", "2", "0", "2", "0", "2", "3", "4"]
