matrix = [
  ["7", "7", "7", "7", "7", "7", "7", "7"],
  ["7", "7", "7", "7", "7", "7", "7", "7"],
  ["7", "7", "7", "7", "7", "7", "7", "7"],
  ["7", "7", "7", "7", "7", "7", "7", "7"],
  ["7", "7", "7", "6", "7", "7", "7", "7"],
  ["7", "7", "7", "7", "7", "7", "7", "7"],
  ["7", "7", "7", "7", "7", "7", "7", "7"],
  ["7", "7", "7", "7", "7", "7", "7", "7"]
]
z = "1"
